language: cpp

compiler:
  - gcc

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "UoodMEO/LGopv+LgjAczpvtgKNxqXmg+Y8F0EGwjBUvpm1ckKcoO2mBOSOPNwX8wPw4isoYHNHJEAa5EojZ17aU0vfbUxeGAqVqPHjGDPe+T7YK3vevHBRojUidxRANlLCPXvOc1SI05BtRxQo6fue2BclTaUCciSqM9SK5bq5H6u/WUJEioGDtqBikhKK0XKxFe/me3DVhDa3H8eXwdqgTkdC2e5vEqnWF6PD/GbtDLWGy4etJ63DKaYjqWme1kbzJ2PY3ExcZKw7DxXvGC1RmXLs/PEO9hDeE0NIbBl/E6G8LiOZb3xBIekPLxDjLum0xdtpvO62T9ptol4hX2RLRz1wmxzh+2ymRIq1YIaXByubXwyFKBCiuDb6+zGN/jayGZdCHDcpRcfkbyrL4uJaYmD3iLtgpwth6KB3N7agzS3qVUicLRVSd1c3LJbXp27km5ryUw6RDZDWYnJFuuSjUjYAB3M/XVmw99tllkR+4Yg+x6jz0Vd03V/rwbv5amD7uedMMYPZtDWi41v89AUAQFaYcbxS9QrnFCV850KjW5yoYvfUGAfBmLGbnSBH71gcUpP6P7g68hg8lZMiVsHTE/PDbgiD3s5PvPDyhxAmodnsVOUn3Jh9Dl+9aF1nuyidGrxgH4VbUjFqv7iD7l3nNRU/es4HMJaLhV+QZofSY="
script:
  - "sonar-scanner"